
spring.profiles: default

server:
  contextPath: /
  port: 8084
  address: localhost
  apiUrl: http://localhost:8083

logging:
  level:
    org:
      springframework:
        web: INFO
  file: spring-stream.log
