
spring.profiles: default

server:
  contextPath: /
  port: 8084
  address: localhost
  publicAddress: http://localhost:4200

logging:
  level:
    org:
      springframework:
        web: INFO
  file: spring-stream.log
