# Default config

spring.profiles: default

server:
  contextPath: /
  port: 8084
  address: localhost
  publicAddress: http://localhost:4200

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      max-swallow-size: -1
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/convrt_me_dev
    username: root
    password: 1234

#cache
  cache:
    type: caffeine
    cache-names: search, video. autocomplete, recommended
    caffeine: 
        spec: maximumSize=500, expireAfterAccess=1h

#jackson config
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ

# Dev config
#spring.profiles: dev, local

logging.level.org.springframework.web: INFO

# Prod config
# spring.profiles: prod

